package main

import (
	"bytes"
	"io/ioutil"
	"os"
	"os/exec"
	"testing"
	"text/template"
)

const README = `<!-- generated by Test_generate_readme, DO NOT EDIT! -->

inventory - Command for listing projects and their versions

This command is used to find and display a set of git projects and
their release information.

## Quick start

{{.Code}}shell
$ go install github.com/gregoryv/inventory
$ inventory -h
{{.Help}}{{.Code}}
`

func Test_generate_readme(t *testing.T) {
	if err := exec.Command("go", "build", ".").Run(); err != nil {
		t.Fatal(err)
	}

	readme := template.Must(template.New("").Parse(README))

	w, _ := os.Create("README.md")
	defer w.Close()

	_ = readme.Execute(w, map[string]interface{}{
		"Code": "```",
		"Help": string(help(t)),
	})
}

func help(t testing.TB) []byte {
	var buf bytes.Buffer
	cmd := exec.Command("./inventory", "-h")
	cmd.Stderr = &buf
	cmd.Stdout = &buf
	defer os.RemoveAll("inventory")
	if err := cmd.Run(); err != nil {
		t.Fatal(err)
	}
	return buf.Bytes()
}

func TestSystem(t *testing.T) {
	s := NewSystem()
	s.SetPaths([]string{".", "."})
	s.SetShowModifiedDate(true)
	s.SetOutput(ioutil.Discard)
	s.Run()
}
